// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vnpc.cpp"
#include "Vnpc___024root__0.cpp"
#include "Vnpc___024unit__0.cpp"
#include "Vnpc__Dpi.cpp"
#include "Vnpc___024root__Slow.cpp"
#include "Vnpc___024root__0__Slow.cpp"
#include "Vnpc___024unit__Slow.cpp"
#include "Vnpc___024unit__0__Slow.cpp"
#include "Vnpc__Syms.cpp"
